apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-mall-maintenance-dev

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: PLACEHOLDER_ECR_URI
  newName: PLACEHOLDER_ECR_URI
  newTag: latest

commonLabels:
  tenant: opsera
  app: mall-maintenance
