apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-mall-maintenance-dev

resources:
- ../../base

labels:
- includeSelectors: false
  pairs:
    environment: dev
    tenant: opsera
    app: mall-maintenance
    managed-by: opsera-c2c

images:
- name: PLACEHOLDER_ECR_URI
  newName: PLACEHOLDER_ECR_URI
  newTag: latest

replicas:
- name: mall-maintenance
  count: 2
