apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-mall-maintenance-dev

resources:
- ../../base

labels:
- includeSelectors: false
  pairs:
    environment: dev
    tenant: opsera
    app: mall-maintenance
    managed-by: opsera-c2c

images:
- name: PLACEHOLDER_ECR_URI
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/mall-maintenance
  newTag: 68d70b2-20260217-112820

replicas:
- name: mall-maintenance
  count: 2
